version: "3"

services:
  server:
    image: node
    working_dir: /app
    container_name: ${APP_NAME}
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
    ports:
      - 3333:3333
    command: >
      bash -c "npm i -g @adonisjs/cli &&
              npm install &&
              adonis serve --dev"